Repository Zelusik/server-main, pull requests merged in 2024-01, with the labels that each got.

#423 회원 정보 수정 API 요청 데이터 중 프로필 이미지 선택값으로 변경
  src/main/java/com/zelusik/eatery/domain/member/dto/request/MemberUpdateRequest.java
Labels: 🐛 bug

#417 리뷰 신고 API 구현
  src/main/java/com/zelusik/eatery/domain/report_review/api/ReportReviewControllerV1.java
  src/main/java/com/zelusik/eatery/domain/report_review/dto/ReportReviewDto.java
  src/main/java/com/zelusik/eatery/domain/report_review/dto/ReportReviewReasonOption.java
  src/main/java/com/zelusik/eatery/domain/report_review/dto/request/ReportReviewRequest.java
  src/main/java/com/zelusik/eatery/domain/report_review/dto/response/GetReportReviewResponse.java
  src/main/java/com/zelusik/eatery/domain/report_review/dto/response/PostReportReviewResponse.java
  src/main/java/com/zelusik/eatery/domain/report_review/entity/ReportReview.java
  src/main/java/com/zelusik/eatery/domain/report_review/exception/ReportReviewNotFoundByIdException.java
  src/main/java/com/zelusik/eatery/domain/report_review/repository/ReportReviewRepository.java
  src/main/java/com/zelusik/eatery/domain/report_review/repository/ReportReviewRepositoryQCustom.java
  src/main/java/com/zelusik/eatery/domain/report_review/repository/ReportReviewRepositoryQCustomImpl.java
  src/main/java/com/zelusik/eatery/domain/report_review/service/ReportReviewCommandService.java
  src/main/java/com/zelusik/eatery/domain/report_review/service/ReportReviewQueryService.java
  src/main/java/com/zelusik/eatery/global/exception/constant/CustomExceptionType.java
  src/test/java/com/zelusik/eatery/unit/domain/report_review/api/ReportReviewControllerV1Test.java
Labels: 💫 enhancement

#426 닉네임으로 회원 존재 여부 조회 시 발생하는 type mismatch 에러 수정
  src/main/java/com/zelusik/eatery/domain/member/repository/MemberRepository.java
  src/main/java/com/zelusik/eatery/domain/member/repository/MemberRepositoryQCustom.java
  src/main/java/com/zelusik/eatery/domain/member/repository/MemberRepositoryQCustomImpl.java
  src/test/java/com/zelusik/eatery/integration/domain/member/repository/MemberRepositoryTest.java
Labels: 🐛 bug

#429 `FoodCategoryValue`에 미등록 데이터 추가
  src/main/java/com/zelusik/eatery/global/common/constant/FoodCategoryValue.java
Labels: ♻️ refactor

#431 리뷰 생성 시 Java heap space out of memory 에러 발생
  Dockerfile.prod
  src/main/java/com/zelusik/eatery/global/config/AsyncConfig.java
Labels: 🐛 bug

#433 회원 정보 수정 시 NicknameDuplicationException 발생하는 문제 수정
  src/main/java/com/zelusik/eatery/domain/member/service/MemberCommandService.java
  src/test/java/com/zelusik/eatery/unit/domain/member/service/MemberCommandServiceTest.java
Labels: 🐛 bug
